// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreatePurchases implements pgx.CopyFromSource.
type iteratorForCreatePurchases struct {
	rows                 []CreatePurchasesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreatePurchases) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreatePurchases) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].BillingID,
		r.rows[0].Mobile,
		r.rows[0].MrpOrNet,
		r.rows[0].Item,
		r.rows[0].Quantity,
		r.rows[0].Discount,
		r.rows[0].SubTotal,
	}, nil
}

func (r iteratorForCreatePurchases) Err() error {
	return nil
}

func (q *Queries) CreatePurchases(ctx context.Context, arg []CreatePurchasesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"purchases"}, []string{"billing_id", "mobile", "mrp_or_net", "item", "quantity", "discount", "sub_total"}, &iteratorForCreatePurchases{rows: arg})
}
