// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Billing struct {
	ID           int64
	User         pgtype.Text
	Mobile       pgtype.Text
	GrandTotal   pgtype.Int4
	FinalizedAmt pgtype.Int4
}

type Expense struct {
	ID               int64
	ReasonForExpense pgtype.Text
	Amount           pgtype.Int4
}

type Inventory struct {
	ID             int64
	BrandOrCompany pgtype.Text
	State          pgtype.Text
	Item           pgtype.Text
	NumOfBoxes     pgtype.Int4
	NumOfCartons   pgtype.Int4
	PricePerCarton pgtype.Int4
	SubTotal       pgtype.Int4
}

type PriceList struct {
	ID    int64
	Price pgtype.Int8
	Item  pgtype.Text
	Brand pgtype.Text
}

type Purchase struct {
	ID        int64
	BillingID int64
	Mobile    pgtype.Text
	MrpOrNet  pgtype.Int4
	Item      pgtype.Text
	Quantity  pgtype.Int4
	Discount  pgtype.Text
	SubTotal  pgtype.Int4
}

type Route struct {
	ID      int64
	Route   string
	Heading string
	Role    string
}

type User struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	Email     pgtype.Text
	Password  pgtype.Text
	Roles     pgtype.Text
}
