// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addInventoryItem = `-- name: AddInventoryItem :one

INSERT INTO inventories (
    brand_or_company,
    state,
    item,
    num_of_boxes,
    num_of_cartons,
    price_per_carton,
    sub_total
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING
    id,
    brand_or_company,
    state,
    item,
    num_of_boxes,
    num_of_cartons,
    price_per_carton,
    sub_total
`

type AddInventoryItemParams struct {
	BrandOrCompany pgtype.Text
	State          pgtype.Text
	Item           pgtype.Text
	NumOfBoxes     pgtype.Int4
	NumOfCartons   pgtype.Int4
	PricePerCarton pgtype.Int4
	SubTotal       pgtype.Int4
}

// ============================================================
// INVENTORY
// ============================================================
func (q *Queries) AddInventoryItem(ctx context.Context, arg AddInventoryItemParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, addInventoryItem,
		arg.BrandOrCompany,
		arg.State,
		arg.Item,
		arg.NumOfBoxes,
		arg.NumOfCartons,
		arg.PricePerCarton,
		arg.SubTotal,
	)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.BrandOrCompany,
		&i.State,
		&i.Item,
		&i.NumOfBoxes,
		&i.NumOfCartons,
		&i.PricePerCarton,
		&i.SubTotal,
	)
	return i, err
}

const countInventory = `-- name: CountInventory :one
SELECT COUNT(*)::BIGINT AS total
FROM inventories
WHERE
    ($1 = '' OR state = $1)
    AND
    ($2 = '' OR item ILIKE '%' || $2 || '%')
`

type CountInventoryParams struct {
	Column1 interface{}
	Column2 interface{}
}

func (q *Queries) CountInventory(ctx context.Context, arg CountInventoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInventory, arg.Column1, arg.Column2)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createBilling = `-- name: CreateBilling :one

INSERT INTO billings (
    "user",
    mobile,
    grand_total,
    finalized_amt
)
VALUES ($1, $2, $3, $4)
RETURNING
    id,
    "user",
    mobile,
    grand_total,
    finalized_amt
`

type CreateBillingParams struct {
	User         pgtype.Text
	Mobile       pgtype.Text
	GrandTotal   pgtype.Int4
	FinalizedAmt pgtype.Int4
}

// ============================================================
// BILLINGS
// ============================================================
func (q *Queries) CreateBilling(ctx context.Context, arg CreateBillingParams) (Billing, error) {
	row := q.db.QueryRow(ctx, createBilling,
		arg.User,
		arg.Mobile,
		arg.GrandTotal,
		arg.FinalizedAmt,
	)
	var i Billing
	err := row.Scan(
		&i.ID,
		&i.User,
		&i.Mobile,
		&i.GrandTotal,
		&i.FinalizedAmt,
	)
	return i, err
}

const createExpense = `-- name: CreateExpense :one

INSERT INTO expenses (
    reason_for_expense,
    amount
)
VALUES ($1, $2)
RETURNING
    id,
    reason_for_expense,
    amount
`

type CreateExpenseParams struct {
	ReasonForExpense pgtype.Text
	Amount           pgtype.Int4
}

// ============================================================
// EXPENSES
// ============================================================
func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense, arg.ReasonForExpense, arg.Amount)
	var i Expense
	err := row.Scan(&i.ID, &i.ReasonForExpense, &i.Amount)
	return i, err
}

const createPurchase = `-- name: CreatePurchase :one
INSERT INTO purchases (
    billing_id,
    mobile,
    mrp_or_net,
    item,
    quantity,
    discount,
    sub_total
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING
    id,
    billing_id,
    mobile,
    mrp_or_net,
    item,
    quantity,
    discount,
    sub_total
`

type CreatePurchaseParams struct {
	BillingID int64
	Mobile    pgtype.Text
	MrpOrNet  pgtype.Int4
	Item      pgtype.Text
	Quantity  pgtype.Int4
	Discount  pgtype.Text
	SubTotal  pgtype.Int4
}

func (q *Queries) CreatePurchase(ctx context.Context, arg CreatePurchaseParams) (Purchase, error) {
	row := q.db.QueryRow(ctx, createPurchase,
		arg.BillingID,
		arg.Mobile,
		arg.MrpOrNet,
		arg.Item,
		arg.Quantity,
		arg.Discount,
		arg.SubTotal,
	)
	var i Purchase
	err := row.Scan(
		&i.ID,
		&i.BillingID,
		&i.Mobile,
		&i.MrpOrNet,
		&i.Item,
		&i.Quantity,
		&i.Discount,
		&i.SubTotal,
	)
	return i, err
}

type CreatePurchasesParams struct {
	BillingID int64
	Mobile    pgtype.Text
	MrpOrNet  pgtype.Int4
	Item      pgtype.Text
	Quantity  pgtype.Int4
	Discount  pgtype.Text
	SubTotal  pgtype.Int4
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    password,
    roles
)
VALUES ($1, $2, $3)
RETURNING
    id,
    created_at,
    updated_at,
    deleted_at,
    email,
    password,
    roles
`

type CreateUserParams struct {
	Email    pgtype.Text
	Password pgtype.Text
	Roles    pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Password, arg.Roles)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Email,
		&i.Password,
		&i.Roles,
	)
	return i, err
}

const findInventoryByID = `-- name: FindInventoryByID :one
SELECT
    id,
    brand_or_company,
    state,
    item,
    num_of_boxes,
    num_of_cartons,
    price_per_carton,
    sub_total
FROM inventories
WHERE id = $1
`

func (q *Queries) FindInventoryByID(ctx context.Context, id int64) (Inventory, error) {
	row := q.db.QueryRow(ctx, findInventoryByID, id)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.BrandOrCompany,
		&i.State,
		&i.Item,
		&i.NumOfBoxes,
		&i.NumOfCartons,
		&i.PricePerCarton,
		&i.SubTotal,
	)
	return i, err
}

const findPaginatedInventory = `-- name: FindPaginatedInventory :many
SELECT
    id,
    brand_or_company,
    state,
    item,
    num_of_boxes,
    num_of_cartons,
    price_per_carton,
    sub_total
FROM inventories
WHERE
    ($1 = '' OR state = $1)
    AND
    ($2 = '' OR item ILIKE '%' || $2 || '%')
ORDER BY id DESC
LIMIT $3
OFFSET $4
`

type FindPaginatedInventoryParams struct {
	Column1 interface{}
	Column2 interface{}
	Limit   int32
	Offset  int32
}

func (q *Queries) FindPaginatedInventory(ctx context.Context, arg FindPaginatedInventoryParams) ([]Inventory, error) {
	rows, err := q.db.Query(ctx, findPaginatedInventory,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Inventory
	for rows.Next() {
		var i Inventory
		if err := rows.Scan(
			&i.ID,
			&i.BrandOrCompany,
			&i.State,
			&i.Item,
			&i.NumOfBoxes,
			&i.NumOfCartons,
			&i.PricePerCarton,
			&i.SubTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findRoutesByRole = `-- name: FindRoutesByRole :many

SELECT
    id,
    route,
    heading,
    role
FROM routes
WHERE role = $1
`

// ============================================================
// ROUTES
// ============================================================
func (q *Queries) FindRoutesByRole(ctx context.Context, role string) ([]Route, error) {
	rows, err := q.db.Query(ctx, findRoutesByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.Route,
			&i.Heading,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUserByEmail = `-- name: FindUserByEmail :one

SELECT
    id,
    created_at,
    updated_at,
    deleted_at,
    email,
    password,
    roles
FROM users
WHERE email = $1
  AND deleted_at IS NULL
`

// ============================================================
// USERS
// ============================================================
func (q *Queries) FindUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Email,
		&i.Password,
		&i.Roles,
	)
	return i, err
}

const getAllExpenses = `-- name: GetAllExpenses :many
SELECT
    id,
    reason_for_expense,
    amount
FROM expenses
ORDER BY id
`

func (q *Queries) GetAllExpenses(ctx context.Context) ([]Expense, error) {
	rows, err := q.db.Query(ctx, getAllExpenses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(&i.ID, &i.ReasonForExpense, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllExpensesTotalAmt = `-- name: GetAllExpensesTotalAmt :one
SELECT COALESCE(SUM(amount), 0)::BIGINT AS total_amount
FROM expenses
`

func (q *Queries) GetAllExpensesTotalAmt(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getAllExpensesTotalAmt)
	var total_amount int64
	err := row.Scan(&total_amount)
	return total_amount, err
}

const getAllPriceList = `-- name: GetAllPriceList :many

SELECT
    id,
    price,
    item,
    brand
FROM price_lists
ORDER BY brand, item
`

// ============================================================
// PRICE LIST
// ============================================================
func (q *Queries) GetAllPriceList(ctx context.Context) ([]PriceList, error) {
	rows, err := q.db.Query(ctx, getAllPriceList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PriceList
	for rows.Next() {
		var i PriceList
		if err := rows.Scan(
			&i.ID,
			&i.Price,
			&i.Item,
			&i.Brand,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumInventorySubTotal = `-- name: SumInventorySubTotal :one
SELECT COALESCE(SUM(sub_total), 0)::BIGINT AS total
FROM inventories
WHERE
    ($1 = '' OR state = $1)
    AND
    ($2 = '' OR item ILIKE '%' || $2 || '%')
`

type SumInventorySubTotalParams struct {
	Column1 interface{}
	Column2 interface{}
}

func (q *Queries) SumInventorySubTotal(ctx context.Context, arg SumInventorySubTotalParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumInventorySubTotal, arg.Column1, arg.Column2)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const updateInventoryDiff = `-- name: UpdateInventoryDiff :exec
UPDATE inventories
SET
    num_of_cartons = $2,
    sub_total = $3
WHERE id = $1
`

type UpdateInventoryDiffParams struct {
	ID           int64
	NumOfCartons pgtype.Int4
	SubTotal     pgtype.Int4
}

func (q *Queries) UpdateInventoryDiff(ctx context.Context, arg UpdateInventoryDiffParams) error {
	_, err := q.db.Exec(ctx, updateInventoryDiff, arg.ID, arg.NumOfCartons, arg.SubTotal)
	return err
}

const updateInventoryState = `-- name: UpdateInventoryState :exec
UPDATE inventories
SET
    state = $2,
    sub_total = $3
WHERE id = $1
`

type UpdateInventoryStateParams struct {
	ID       int64
	State    pgtype.Text
	SubTotal pgtype.Int4
}

func (q *Queries) UpdateInventoryState(ctx context.Context, arg UpdateInventoryStateParams) error {
	_, err := q.db.Exec(ctx, updateInventoryState, arg.ID, arg.State, arg.SubTotal)
	return err
}
